name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute once every 24 hours (midnight UTC)
    - cron: "0 0 * * *"
  workflow_dispatch: # allow manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Use the GitHub Profile Summary Cards action
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{MY_PERSONAL_ACCESS_TOKEN}}
        with:
          USERNAME: ${{ github.raviknce0509 }}

      # Optionally add caching (for speed improvement)
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-